### ISSUE TITLE
Full screen not work

### ISSUE THREAD

**Issue by Naguchennai** [JarvanMo/ExoPlayerVideoView#1]
Full screen not work. also exoplayer r2.1.1 not support

**Comment by JarvanMo** [comment]
@naguchennai  The full screen should be managed by yourself in the current version.
```java
videoView.changeOrientation();
```

and
```java
        videoView.setFullScreenListener(new ExoVideoPlaybackControlView.ExoClickListener() {
            @Override
            public void onClick(View view, boolean isPortrait) {
                videoView.changeOrientation();
            }
        });
```
I'll change this in the future. The orientation of video should depend on system by default.

I'll update exoplayer to r2.1.1 as soon as possible.
Thanks~

**Comment by JarvanMo** [comment]
commit something new
