### ISSUE TITLE
how to pars mediaSource from another Activity to ExoVideoView activity?

### ISSUE THREAD

**Issue by forotan1** [JarvanMo/ExoPlayerVideoView#11]
first thanks for such a good library.
i want to pars url string from X activity to exovideoview Activity by Intent by i couldnt, can you please guide me how to do it?
and also how i can change quality of stream in playerView.
thanks

**Comment by JarvanMo** [comment]
Do you mean :
in `XActivity`:
```java
Intent intent = new Intent(context,ExoVideoActivity.class);
intent.put("key_url",url);
startActivity(intent);
```
in `ExoVideoActivity`:
```java
String url = getIntent().getStringExtra("key_url");
```

The support for different quality of stream is under development.For now,you add a custom view to `ExoVideoView` when landscape by 
```java
videoView.addViewToControllerWhenLandscape(view);
```
Then you can implements it by yourself.

**Comment by forotan1** [comment]
thanks for your quick respons.
actually it worked.

**Comment by JarvanMo** [comment]
2.0.0 has been released.
