### ISSUE TITLE
app will freeze when video hasn't been loaded, if video link is broken, then the app will freeze

### ISSUE THREAD

**Issue by MacauNext** [JarvanMo/ExoPlayerVideoView#12]
app will freeze when video hasn't been loaded, if video link is broken, then the app will freeze, I suggest, the video should be loaded after entering the activity!

**Comment by JarvanMo** [comment]
@MacauNext  Thanks.I'm rewriting this project.

**Comment by MacauNext** [comment]
glad to to your quick improvement, there still some problems, in the landscape full view, the Back arrow is not working. 
And you should put the Play button in the video player for user to click to play more convenient, also you can set a thumbnail or background for the video. :)

**Comment by JarvanMo** [comment]
Thanks for your report.I'll add these features in the future.

**Comment by JarvanMo** [comment]
2.0.0 has been released.
