### ISSUE TITLE
How to add subtitle ?

### ISSUE THREAD

**Issue by herudi** [JarvanMo/ExoPlayerVideoView#14]
How to add subtitle ?

**Comment by JarvanMo** [comment]
```java
 videoView.getSubtitleView();
```

**Comment by tmxd09887** [comment]
是这样吗？

SubtitleView subtitleView = videoView.getSubtitleView();

subtitleView怎么加载到exoplayer呢

**Comment by JarvanMo** [comment]
@tmxd09887 subtitleView其实一起画到了```xml exo_video_view.xml ```里了。

**Comment by tmxd09887** [comment]
@JarvanMo 怎么把远程字幕文件加到里面呢？

**Comment by JarvanMo** [comment]
@tmxd09887  这个代码里有。因为这个项目是基于exo的，exo里有怎么使用网络subtitle

**Comment by JarvanMo** [comment]
@herudi The ExoPlayer demo provide a smaple.

**Comment by pulpcorn** [comment]
Hi @JarvanMo 

I'm trying to implement subtitles to the video but I can't find any samples.
I read your code and realize the method getSubtitleView().
But to able to implement it, I have to add list of Cues, which don't have start time or end time or duration time to show the text.

Can you help me?

Thanks.
