### ISSUE TITLE
Do not work on Meizu phone (Android 7.1),the log info is shown below

### ISSUE THREAD

**Issue by onecoders** [JarvanMo/ExoPlayerVideoView#15]
Do not work on Meizu phone (Android 7.1),the log info is shown below
![99e227075ff366b7da1bdda15934cc43](https://user-images.githubusercontent.com/3477738/38799206-62e021e8-4196-11e8-8e37-bcdeba81f58b.png)

**Comment by JarvanMo** [comment]
[see here](https://github.com/google/ExoPlayer/issues/4127)
