### ISSUE TITLE
麻烦问下怎么在代码里调用设置视频的比例呢?

### ISSUE THREAD

**Issue by SeekMyCosmic** [JarvanMo/ExoPlayerVideoView#2]
用了setResizeMode不行啊.

**Comment by JarvanMo** [comment]
@SeekMyCosmic  `videoView.setResizeMode(mode)`提供了四种视频适应比例。
RESIZE_MODE_NONE：不进行调整，就是直接进行拉伸。
RESIZE_MODE_FIT：自动按视频原比例进行调整。
RESIZE_MODE_FIXED_WIDTH：宽度固定，高度根据比例调整。
RESIZE_MODE_FIXED_HEIGHT：高度固定，宽度根据比例调整。
我刚刚试了一下是好用的啊。

**Comment by SeekMyCosmic** [comment]
抱歉, 是我的视频出了问题. 
你这个做的很好.
