### ISSUE TITLE
Zoom Gesture

### ISSUE THREAD

**Issue by taimoorMalik** [JarvanMo/ExoPlayerVideoView#20]
Hello mate!
Can you please tell me how to implement zoom gesture in video player like brightness and volume control?

**Comment by JarvanMo** [comment]
@taimoorMalik 
see ```exoplayerview/src/main/java/com/jarvanmo/exoplayerview/gesture/VideoGesture.java```.
you can star or fork this project for more information

**Comment by taimoorMalik** [comment]
Hello thanks for your reply i have star your project i also explore video gesture class but cant figure out how to enable zoom gesture, noob here :)

**Comment by JarvanMo** [comment]
There's a lot of math here。I can't figure out how it works here.The gesture class works with a view and you should override its touch event if you want to implement your own zoom gesture.

**Comment by taimoorMalik** [comment]
I have follow this post for zoom gesture it work alone but when i try to implement it in this project it wont detect any zoom gesture https://github.com/Manuiq/ZoomableTextureView. Can you please look into it as its already done all the math required for zoom gesture.

**Comment by JarvanMo** [comment]
do you disable the playback controller?The gesture in this project works with the playback controller.The controller will interrupt touch event.Maybe you should override the playback controller

**Comment by taimoorMalik** [comment]
Well i need all this project  gesture + zoom gesture from that project and i don't know how to do it can you please help me to do this?

**Comment by JarvanMo** [comment]
I will have a try.

**Comment by taimoorMalik** [comment]
Ok thanks i will wait for it need it desperately thanks alot!

**Comment by JarvanMo** [comment]
![image](https://user-images.githubusercontent.com/11608487/42307577-7bb0d768-8065-11e8-9d2c-bf5e63668881.png)
I override the touch event of  ZoomableTextureView as above.
Remove useless code in VideoGesture and OnVideoGestureChangeListener.
Override the touch event of  ZoomableTextureVie in the following states:```MotionEvent.ACTION_DOWN```,```MotionEvent.ACTION_UP```,```MotionEvent.ACTION_MOVE```.
VideoGesture only works when  ZoomableTextureView can't be zoomed.

Try it.
Hope it helps.

**Comment by taimoorMalik** [comment]
Hello, "VideoGesture only works when ZoomableTextureView can't be zoomed" it means i can't uses gesture of brightness seek and volume when zoomed? right?

**Comment by JarvanMo** [comment]
Right.

**Comment by taimoorMalik** [comment]
Can we handle it with a button in that case will it work? button of zoom in and out?

**Comment by JarvanMo** [comment]
Maybe

**Comment by taimoorMalik** [comment]
Hmm thank you very much for your help much appreciated your effort.

**Comment by taimoorMalik** [comment]
I just tried the above code and its not working still only volume etc gesture working!
