### ISSUE TITLE
how can i show the loading dialog

### ISSUE THREAD

**Issue by priteshc** [JarvanMo/ExoPlayerVideoView#24]

**Comment by JarvanMo** [comment]
I'll add a loading progress bar later.

**Comment by JarvanMo** [comment]
@priteshc do you mean that?

**Comment by priteshc** [comment]
also  how to identify that the video loading or not

**Comment by JarvanMo** [comment]
@priteshc the playback state is `Player.STATE_BUFFERING` and `playWhenReady` is false. Hope it works.

**Comment by JarvanMo** [comment]
@priteshc 2.0.9 released.And I add a loading bar.Try it!

**Comment by priteshc** [comment]
ok thanks

**Comment by priteshc** [comment]
please give the sample of playback state

**Comment by JarvanMo** [comment]
```java
  if (playbackState == Player.STATE_IDLE || playbackState == Player.STATE_BUFFERING) {
           //loading
   } else if (playbackState == Player.STATE_READY && player.getPlayWhenReady() || playbackState == Player.STATE_ENDED) {
              //
   }
```

maybe it's not totally correct.If you find a better way,tell me or give PR.Thanks.

**Comment by priteshc** [comment]
what is palyback state?

**Comment by priteshc** [comment]
whose object it is?

**Comment by JarvanMo** [comment]
```java
player.getPlaybackState(); 
```
Or give listener `Player.DefaultEventListener` to the player.

**Comment by priteshc** [comment]
hyyy m not getting listner for videoview plzzz help me as possibe as

**Comment by JarvanMo** [comment]
@priteshc There are 2 ways to create ExoPlayer:
* create a player by ExoVideoView.
* create a player yourself and then pass it to ExoVideoView.
You can set a listener for ExoPlayer instead.And you can access ExoPlayer via `exoVideoView.getPlayer()`.

**Comment by JarvanMo** [comment]
For details,you can search `EventListener` in my `PlaybackControlView` file.

**Comment by priteshc** [comment]
xovideoview.getplayer(). which listnener i have add?

**Comment by JarvanMo** [comment]
`Player.DefaultEventListener` @priteshc

**Comment by JarvanMo** [comment]
Hoep it works.

**Comment by priteshc** [comment]
exovideoview.getplayer().DefaultEventListener is it?

**Comment by JarvanMo** [comment]
@priteshc  a full example:
```java
   videoView.getPlayer().addListener(new Player.DefaultEventListener() {
        });
        videoView.getPlayer().addVideoListener(new VideoListener() {
            @Override
            public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio) {
                
            }

            @Override
            public void onRenderedFirstFrame() {

            }
        });
```
override the methods you want.

**Comment by priteshc** [comment]
inside i how can i checked is video buffering or not

**Comment by JarvanMo** [comment]
see above.

**Comment by priteshc** [comment]
videoView.getPlayer().addListener(new Player.DefaultEventListener() {
        });

when i added above code 


           }

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.addListener(com.google.android.exoplayer2.Player$EventListener)' on a null object reference

**Comment by JarvanMo** [comment]
call this method `addListener` after you pass a player to ExoVideoView or `exoVideoView.play(source)`
by the way ,can you speak Chinese?

**Comment by priteshc** [comment]
no brother

**Comment by JarvanMo** [comment]
It seems you're new to Java.

**Comment by priteshc** [comment]
how to hide back button of the videoview

**Comment by JarvanMo** [comment]
not supported now.Maybe add this feature in the next version.
Now two ways to solve this:
* clone this project and add it to your project as a library
* override playback controller.Keep the same ids for faster development.
Also you can wait my push.Maybe next week.

**Comment by JarvanMo** [comment]
@priteshc 2.1.0 is released now.You can hide some widgets as you like in this version.See `README` for more details.

**Comment by JarvanMo** [comment]
@priteshc if you like `ExoVideoView`,star it please.
