### ISSUE TITLE
resume() not working at all

### ISSUE THREAD

**Issue by yuriyvolkhonsky** [JarvanMo/ExoPlayerVideoView#26]
So simple problem, and I can't google any ideas about this. Maybe I'm doing something wrong?
There is an ExoVideoView in a fragment, I start playing by
```
mVideoView.setUseController(false);
mVideoView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_FIT);
mVideoView.setRepeatToggleModes(RepeatModeUtil.REPEAT_TOGGLE_MODE_ALL);
mediaSource = new SimpleMediaSource("some url");
mVideoView.play(mediaSource, true);
mVideoView.getPlayer().setRepeatMode(RepeatModeUtil.REPEAT_TOGGLE_MODE_ALL);
```
Then, I pause playback with
`mVideoView.pause()`
it works fine. But then,
`mVideoView.resume()`
don't give any effect :-(
`mVideoView.play(mediaSource, mVideoView.getPlayer().getCurrentPosition());`
works fine, but playback is restored only after black blinking, which is not good.. Any ideas?
PS. When using Controller controls - pause/resume works fine. But i need Play/Pause button outside the fragment. Tried mVideoView.requestFocus() - not helped.

**Comment by JarvanMo** [comment]
Thanks for report.I'll have a check.

**Comment by JarvanMo** [comment]
@yuriyvolkhonsky I can't figure out the problem because it never happened here.Maybe the exoplayer crashed(actually ,it's codec) .See outputs for more details.

**Comment by JarvanMo** [comment]
@yuriyvolkhonsky  Could you provide more code?

**Comment by JarvanMo** [comment]
@yuriyvolkhonsky I can't figure out what's wrong because it never happened.Could you provide more code?

**Comment by yuriyvolkhonsky** [comment]
Oh, I'm so sorry - didn't noticed version 2.0.1 is used in my project :-((
Sorry again for my blindness..
And current version 2.1.0 seems to be much different, so it will be a lot
of work to upgrade my existing code... Don't u remember if there was an
issue in 2.0.1 with resume()? Maybe there's a workaround

вт, 4 сент. 2018 г. в 16:12, JarvanMo <notifications@github.com>:

**Comment by JarvanMo** [comment]
The are   not too many api  changes  since 2.0.0. So if you never changed my code,there's no too much  work to do.
I'm sorry I forget if there was an issue in 2.0.1 with resume(). 
Maybe I fixed this problem in a particular version.
If this project helps u,give a star please.
