### ISSUE TITLE
local HD Video is not seekable why? 

### ISSUE THREAD

**Issue by khizar1556** [JarvanMo/ExoPlayerVideoView#29]
when i am trying to play HD videos resolution 1080 or above from my sd card video is started everything is fine but when i am seek forward it will play from start position why? if i am try to pay that uri to exo player demo application then timebar is disable can anyone please help me to sort out this problem

**Comment by khizar1556** [comment]
@JarvanMo Can you please use to remux the video with ffmpeg in this ?

**Comment by JarvanMo** [comment]
you mean compile this project with ffmpeg?

**Comment by khizar1556** [comment]
@JarvanMo  see this i asked the same question on exoplayer library they told me to remux the videos with ffmpeg will help you 
[https://github.com/google/ExoPlayer/issues/4856](https://github.com/google/ExoPlayer/issues/4856)
see in this link 
will you help me to make it perfect?

**Comment by JarvanMo** [comment]
if you want to use both ExoPlayer and ffmpeg, you should compile ExoPlayer with ffmpeg yourself.The docs are [here](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg).

**Comment by khizar1556** [comment]
@JarvanMo basically sir i tried so many times but i failed every time i want you to help me to make this thing just becuase seekbar is disabled please sir

**Comment by JarvanMo** [comment]
@khizar1556 Are you in a hurry? Maybe I can help you after holidays. Tell me your operation system.

**Comment by khizar1556** [comment]
@JarvanMo i am in hurry but i will wait for you sir i will be very thankful to you if you solve this issue for me i am using windows 10.my operating system is windows 10

**Comment by khizar1556** [comment]
@JarvanMo Are you free now?

**Comment by JarvanMo** [comment]
yeah,I'll try it very soon.

**Comment by JarvanMo** [comment]
@khizar1556  you'd better compile ffmpeg with linux or macos

**Comment by khizar1556** [comment]
@JarvanMo i just have windows and i dont have mac or linux so that's why i am asking you to help me

**Comment by JarvanMo** [comment]
cygwin maybe helps

**Comment by JarvanMo** [comment]
Linux On Windows maybe helps too

**Comment by khizar1556** [comment]
you mean to say virtually?

**Comment by khizar1556** [comment]
ok will try it

**Comment by JarvanMo** [comment]
No.Windows10 has subsystem called WSL.WSL allow you use Linux such as ubuntu on Windows directly without a VM.

**Comment by JarvanMo** [comment]
you can get a linux from app sotre

**Comment by khizar1556** [comment]
oh thats great but  is that necessary to install android studio into  linux?

**Comment by JarvanMo** [comment]
No.Actually we need Linux or MacOS to compile ffmpeg.Once you've done that, Linux or MacOS is over.After you compile ffmpeg ,you'll get a collection of *libXXX.so* files and that's what you want.Do as the *README* do.

**Comment by khizar1556** [comment]
ok if i face some problem during this i will contact you thanks for help :)

**Comment by khizar1556** [comment]
will you please make me this ? i tried it but i am failed

**Comment by ranakhizar1556** [comment]
@JarvanMo  need help please

**Comment by JarvanMo** [comment]
@khizar1556 what's wrong

**Comment by ranakhizar1556** [comment]
@JarvanMo Hd files not seekable 4k mkv matroska files are not seekable every video i downloaded from youtube using idm it play on every player but not in exoplayer please help me to do this i cant be able to do that
