### ISSUE TITLE
全屏功能不能用

### ISSUE THREAD

**Issue by wanghc0** [JarvanMo/ExoPlayerVideoView#3]
横屏状态下按钮没有消失

![landscape](https://cloud.githubusercontent.com/assets/17804057/24072605/914250d6-0c24-11e7-9d02-a56bc074cb7c.png)
![potrait](https://cloud.githubusercontent.com/assets/17804057/24072606/915f2cc4-0c24-11e7-8003-8441a476e540.png)

**Comment by JarvanMo** [comment]
@Wangct23  真正的横屏需要手动控制的，我提供的横屏只是UI级别的，您需要自己监听传感器的方向。之所以这么设计，是我实际工作中决定。可能在后续版本中添加自动支持。

**Comment by JarvanMo** [comment]
@Wangct23 新版本已经得重新做了全屏。
