### ISSUE TITLE
Detect when Video Play Finish

### ISSUE THREAD

**Issue by TuonBondol** [JarvanMo/ExoPlayerVideoView#30]
Sorry to ask How to detect when video play is complete

Thank!

**Comment by JarvanMo** [comment]
Add EventListener to exoplayer and release it.

**Comment by JarvanMo** [comment]
if you're using a built-in player ,you can call exoVideoView.releasePlayer()

**Comment by TuonBondol** [comment]
I am using your library to play the list of the video, what I want is, when I play first video1 complete, I need to auto play to video2 and move on, that why I need to detect when the first video is finish then trigger it to auto play after that, how can I make that with you library, 

Thank you

**Comment by TuonBondol** [comment]
@JarvanMo I found the answer to get it, 
Thank you for your support 👍

**Comment by deny-joefakri** [comment]
@TuonBondol  can you give sample code to detect when finish the video? please,
