### ISSUE TITLE
Disable Drag up and Down to adjust brightness and volume

### ISSUE THREAD

**Issue by TuonBondol** [JarvanMo/ExoPlayerVideoView#31]

**Comment by TuonBondol** [comment]
Awesome Library you have create here, I have one question to ask, is it possible to disable auto adjust brightness and volume when we drag up and down inside player frame, I don't know if you already have that function or not, I just seem can not find it.

Thank you

**Comment by JarvanMo** [comment]
it seems that it's impossible now. I'll add the this feature later.

**Comment by JarvanMo** [comment]
@TuonBondol hey, let's disable the gesture now:
```
videoView.setGestureEnabled(false);
```
also we can also do this in your xml file:
```
app:enableGesture="false"
```

**Comment by TuonBondol** [comment]
@JarvanMo I can use xml in this com.jarvanmo.exoplayerview.ui.ExoVideoView package, where should I use it in xml file, plus I can't call it in code with this videoView.setGestureEnabled either, can you explain a bit more, where to use it correctly

Thank

**Comment by JarvanMo** [comment]
upgrade to 2.1.3。

**Comment by TuonBondol** [comment]
@JarvanMo I see now, I already try it! It work perfectly! 

Thank you so much :)
