### ISSUE TITLE
Gradle sync Issues

### ISSUE THREAD

**Issue by 4droidiz** [JarvanMo/ExoPlayerVideoView#38]
ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-19:19 to override.

Gradle sync failed: Could not find method compileOptions() for arguments [build_97ux8l4vqnh6xzchvcyv8ox6l$_run_closure2@646f9dbe] on project ':app' of type org.gradle.api.Project.

**Comment by JarvanMo** [comment]
add 'tools:replace="android:appComponentFactory"' to element at AndroidManifest.xml:5:5-19:19 to override.
