### ISSUE TITLE
duplicate value for resource

### ISSUE THREAD

**Issue by SujeetKr9** [JarvanMo/ExoPlayerVideoView#50]
Getting this error after adding the dependency 

implementation 'com.jarvanmo:exoplayerview:2.1.3'

AAPT: error: duplicate value for resource 'attr/textColor' with config ''.

**Comment by JarvanMo** [comment]
I will check it this weekend

**Comment by JarvanMo** [comment]
Have you upgrade to the newest one?

**Comment by matrimonial-suhane** [comment]
Ya. In version 2.1.4, it is working fine.
Maybe some bug in version 2.1.3.

**Comment by SujeetKr9** [comment]
Ya. I Upgraded to version 2.1.4 it's working fine.
Maybe some bug in version 2.1.3.
