### ISSUE TITLE
Not able to update library because of some issues

### ISSUE THREAD

**Issue by mnk98** [JarvanMo/ExoPlayerVideoView#53]
If we update library from `com.jarvanmo:exoplayerview:2.1.3` to `com.jarvanmo:exoplayerview:2.1.5` .. its says `AdsMediaSource.MediaSourceFactory` does not found as i am using video with ads in different activity. but new update is affecting this. and if i do not update library then getting error 

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/drm/DefaultDrmSessionManager$EventListener;
        at com.jarvanmo.exoplayerview.ui.ExoVideoView.play(ExoVideoView.java:865)
        at com.jarvanmo.exoplayerview.ui.ExoVideoView.play(ExoVideoView.java:852)

on 
val mediaSource = SimpleMediaSource(path) //uri also supported
val videoView = promptsView.findViewById<ExoVideoView>(R.id.videoView)
videoView.play(mediaSource) // getting error here

**note using ExoPlayer library**
 implementation 'com.google.android.exoplayer:exoplayer:2.11.0'
 implementation 'com.google.android.exoplayer:extension-ima:2.9.1'
 implementation 'com.google.android.exoplayer:extension-mediasession:2.10.0'

**Comment by mnk98** [comment]
no need, sorry

**Comment by JarvanMo** [comment]
I'll update this library these days.
