### ISSUE TITLE
Is there any ways to detect click/touch?

### ISSUE THREAD

**Issue by pulpcorn** [JarvanMo/ExoPlayerVideoView#59]
Is there any way to detect click/touch when controller is showing?

I noticed that when Controller is showing, the VideoGesture onTouch will handle the event when touch but there is no any events handle for only 1 touch (like click event) right?

I want to detect touch event to able to show/hide something like Toolbar, controller, etc.... 

Thanks.

**Comment by JarvanMo** [comment]
Not supported now. I'll consider this next release------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Vu&amp;nbsp;Ho&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月6日(星期五) 晚上8:34
收件人:&nbsp;&quot;JarvanMo/ExoVideoView&quot;<ExoVideoView@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JarvanMo/ExoVideoView] Is there any ways to detect click/touch? (#59)

**Comment by pulpcorn** [comment]
Hi @JarvanMo 

I will wait for your next release.
Here is my solution:
1. Hide controller by set use_controller = false
2. Implement my own onTouch event or seekbar etc...

Thanks.
