### ISSUE TITLE
你好,请问ExoPlayer支不支持Rtsp流

### ISSUE THREAD

**Issue by RedTowerMountain** [JarvanMo/ExoPlayerVideoView#6]
例如播放rtsp://192.168.48.1/stream2 这是个车载行车记录仪的流 返回的错误是解析Url失败

**Comment by JarvanMo** [comment]
https://google.github.io/ExoPlayer/supported-formats.html

https://github.com/google/ExoPlayer/issues/55

@RedTowerMountain 参看这2个
