### ISSUE TITLE
关于亮度及音量手势

### ISSUE THREAD

**Issue by jyh149129** [JarvanMo/ExoPlayerVideoView#7]
在小米2s上测试，感觉对比其他app的手势调节亮度和音量，不够平滑和流畅；而且有时候滑动了一段距离也没有反应，指示器也没显示

**Comment by jyh149129** [comment]
ps：希望作者持续更新下exoplayer版本，很不错的播放器

**Comment by jyh149129** [comment]
还有两个问题
1、对于源是hls的时候，可否不实时更新进度和时长显示，否则每次下载到hls的每个ts文件进度条都会重新计算，造成进度条一直在动，并走不到结尾
2、对于直播类源，是否有个开关，可以禁止对进度条的操作，类似节操播放器那样直接锁定进度到最后，时长显示为0就好

**Comment by JarvanMo** [comment]
我会考虑的。

**Comment by jyh149129** [comment]
嗯，谢谢作者的这个库，封装的很不错
